name: RevStock CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build & Test (CI)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # ---------- RESTORE & BUILD ----------
    - name: Restore & Build All Services
      run: |
        dotnet restore
        dotnet build -c Release --no-restore

    # ---------- RUN TESTS ----------
    - name: Run Unit Tests
      run: |
        dotnet test --no-build --verbosity normal


  docker-build-push:
    name: Docker Build & Push (CD)
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Auth Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/revstock-auth:latest ./AuthService
        docker push ${{ secrets.DOCKER_USERNAME }}/revstock-auth:latest

    - name: Build & Push User Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/revstock-user:latest ./UserService
        docker push ${{ secrets.DOCKER_USERNAME }}/revstock-user:latest

    - name: Build & Push Inventory Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/revstock-inventory:latest ./InventoryService
        docker push ${{ secrets.DOCKER_USERNAME }}/revstock-inventory:latest

    - name: Build & Push Procurement Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/revstock-procurement:latest ./ProcurementService
        docker push ${{ secrets.DOCKER_USERNAME }}/revstock-procurement:latest

    - name: Build & Push Sales Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/revstock-sales:latest ./SalesService
        docker push ${{ secrets.DOCKER_USERNAME }}/revstock-sales:latest

    - name: Build & Push API Gateway Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/revstock-apigateway:latest ./ApiGateway
        docker push ${{ secrets.DOCKER_USERNAME }}/revstock-apigateway:latest
